import { useQuery } from "@tanstack/react-query";
import { apiFetch } from "@/lib/api";

/**
 * PRD-0006 S12 — "最新洞察" generated by a local agent reading the user's real
 * on-disk works, then filtered server-side through D3 (insight-guardrail) so no
 * insight ever cites a never-measured metric (retention / 完播 / hook-timing).
 *
 * The endpoint always returns 200 with `{ insights: [] }` on any failure
 * (honest empty state, not an error page), so this adapter only has to defend
 * against a malformed/missing array.
 */

export const HONEST_INSIGHTS_QUERY_KEY = ["analytics", "insights"] as const;

export interface HonestInsight {
  date: string;
  body: string;
  tag: string;
}

interface InsightsResponse {
  insights?: unknown;
}

function adapt(raw: InsightsResponse): HonestInsight[] {
  if (!raw || !Array.isArray(raw.insights)) return [];
  return raw.insights
    .filter(
      (i): i is HonestInsight =>
        !!i &&
        typeof i === "object" &&
        typeof (i as HonestInsight).body === "string" &&
        (i as HonestInsight).body.trim().length > 0,
    )
    .map((i) => ({
      date: typeof i.date === "string" ? i.date : "",
      body: i.body,
      tag: typeof i.tag === "string" ? i.tag : "",
    }));
}

export function useHonestInsights() {
  return useQuery({
    queryKey: HONEST_INSIGHTS_QUERY_KEY,
    queryFn: async () => {
      const raw = await apiFetch<InsightsResponse>("/api/analytics/insights");
      return adapt(raw);
    },
    // Insight synthesis spawns an agent — don't refetch aggressively.
    staleTime: 5 * 60_000,
  });
}
